### ISSUE TITLE
Repackaging of Jackson in `jersey-media-json-jackson`

### ISSUE THREAD

**Issue by fabriziocucci** [jersey/jersey#3636]
Absurd as it may seem, it is probably more likely to win the lottery twice in a row rather than **not** having a dependency conflict due Jackson in a new project!

All kidding aside, It would be nice to repackage Jackson in `jersey-media-json-jackson` or, at very lest, have a complementary artifact which repackage Jackson (e.g. `jersey-media-json-jackson-shaded` as an alternative to the plain `jersey-media-json-jackson`).

**Comment by pavelbucek** [comment]
well :-) we won't do that :)

I can see where you are going and that it actually could be useful, but.. Jersey doesn't repackage whole jackson, only JAX-RS related artifacts. And it was really only a bad workaround (caused by the absence of jackson release with this fix: https://github.com/FasterXML/jackson-jaxrs-providers/pull/98 ).

The plan actually REVERT that, when possible.

If we'd go this way, then we'd have lots of requests to "repackage this and that" and then consequent - update this repackaged version etc.. we don't want to replicate what maven/dependency management does of us..

**Comment by fabriziocucci** [comment]
Well...at least I tried! :)

Thanks for taking the time to explain the Jersey policy about repackaging.

> we don't want to replicate what maven/dependency management does of us..

I understand that but, in general, there are always exceptions that it's worth considering (like the repackaging of guava in jersey 2.25.x) which come with a little cost but make the life of your users way easier!
