### ISSUE TITLE
org.glassfish.jersey.server.ContainerRequest not implemented Serializable

### ISSUE THREAD

**Issue by idrissov** [jersey/jersey#3643]
We use jersey 2.25.1. 
We send HttpHeaders to remote ejb bean that located in other artifact and faced with following error
"Failed to serialize org.glassfish.jersey.server.ContainerRequest"

Why org.glassfish.jersey.server.ContainerRequest doesn't implement Serializable?

**Comment by pavelbucek** [comment]
Because it is not meant to be serialized.

Just look at the methods and what functionality do they provide. How that could be supported when invoked on the remote side? (one example to cover everything - entity operations do work directly on top of the underlying tcp connection, which cannot be serialized or moved to "another node").

BTW, this thread looks is more a question than anything else - please use mailing list (https://javaee.groups.io/g/jersey) for questions/discussions and keep issue tracker for issues.

Thanks and regards,
Pavel

**Comment by idrissov** [comment]
thanks for reply
